export const quotes = [
  "Your hard work today is the foundation for your success tomorrow.",
  "Opportunities don't happen, you create them.",
  "The only way to do great work is to love what you do.",
  "Success is not final; failure is not fatal: it is the courage to continue that counts.",
  "Believe you can and you're halfway there.",
  "Dream big and dare to fail.",
  "The future depends on what you do today.",
  "Skill is the unified force of experience, intellect and passion.",
  "Don't wait for opportunity. Create it.",
  "Action is the foundational key to all success.",
  "Quality is not an act, it is a habit.",
  "The expert in anything was once a beginner.",
  "Your talent determines what you can do. Your motivation determines how much you are willing to do.",
  "Hard work beats talent when talent doesn't work hard.",
  "Work hard in silence, let your success be your noise.",
  "The only place where success comes before work is in the dictionary.",
  "Small daily improvements are the key to staggering long-term results.",
  "Success usually comes to those who are too busy to be looking for it.",
  "Opportunities are like sunrises. If you wait too long, you miss them.",
  "The secret of getting ahead is getting started.",
  "Great things never come from comfort zones.",
  "Focus on being productive instead of busy.",
  "Efficiency is doing things right; effectiveness is doing the right things.",
  "Don't be afraid to give up the good to go for the great.",
  "The harder you work for something, the greater you'll feel when you achieve it.",
  "Dream it. Wish it. Do it.",
  "Success is the sum of small efforts, repeated day in and day out.",
  "Don't stop when you're tired. Stop when you're done.",
  "Wake up with determination. Go to bed with satisfaction.",
  "Do something today that your future self will thank you for.",
  "Little things make big days.",
  "It's going to be hard, but hard does not mean impossible.",
  "Don't wait for the right opportunity: create it.",
  "Sometimes we're tested not to show our weaknesses, but to discover our strengths.",
  "The key to success is to focus on goals, not obstacles.",
  "Dream it. Believe it. Build it.",
  "Success starts with self-discipline.",
  "Be so good they can't ignore you.",
  "Stay hungry. Stay foolish.",
  "The distance between dreams and reality is called action.",
  "If you want to achieve greatness stop asking for permission.",
  "I find that the harder I work, the more luck I seem to have.",
  "Success is walking from failure to failure with no loss of enthusiasm.",
  "All our dreams can come true if we have the courage to pursue them.",
  "Opportunities are everywhere if you know how to look for them.",
  "Work for it more than you hope for it.",
  "Don't wish for it. Work for it.",
  "The way to get started is to quit talking and begin doing.",
  "Passion is the difference between having a job and having a career.",
  "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "Do what you can, with what you have, where you are.",
  "The best way to predict the future is to create it.",
  "It does not matter how slowly you go as long as you do not stop.",
  "Everything you've ever wanted is on the other side of fear.",
  "The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack of will.",
  "Motivation is what gets you started. Habit is what keeps you going.",
  "Don't count the days, make the days count.",
  "Hard work is a two-way street. You get back exactly what you put in.",
  "The road to success is always under construction.",
  "If it was easy, everyone would do it.",
  "Don't let yesterday take up too much of today.",
  "Experience is the name everyone gives to their mistakes.",
  "The power of imagination makes us infinite.",
  "Believe in yourself and all that you are.",
  "You are never too old to set another goal or to dream a new dream.",
  "The only person you are destined to become is the person you decide to be.",
  "Start where you are. Use what you have. Do what you can.",
  "Success is not the key to happiness. Happiness is the key to success.",
  "The will to win, the desire to succeed, the urge to reach your full potential... these are the keys that will unlock the door to personal excellence.",
  "Act as if what you do makes a difference. It does.",
  "You don't have to be great to start, but you have to start to be great.",
  "Success is liking yourself, liking what you do, and liking how you do it.",
  "Change your thoughts and you change your world.",
  "Strive not to be a success, but rather to be of value.",
  "I am not a product of my circumstances. I am a product of my decisions.",
  "The most difficult thing is the decision to act, the rest is merely tenacity.",
  "Whatever the mind can conceive and believe, it can achieve.",
  "Your time is limited, so don't waste it living someone else's life.",
  "Winning isn't everything, but wanting to win is.",
  "Whether you think you can or you think you can't, you're right.",
  "The best revenge is massive success.",
  "The mind is everything. What you think you become.",
  "An unexamined life is not worth living.",
  "Eighty percent of success is showing up.",
  "Your life does not get better by chance, it gets better by change.",
  "Success is not just about what you accomplish in your life; it's about what you inspire others to do.",
  "What you do today can improve all your tomorrows.",
  "The only way to achieve the impossible is to believe it is possible.",
  "Don't watch the clock; do what it does. Keep going.",
  "Keep your eyes on the stars, and your feet on the ground.",
  "You can't cross the sea merely by standing and staring at the water.",
  "A journey of a thousand miles begins with a single step.",
  "Failure is simply the opportunity to begin again, this time more intelligently.",
  "Hardships often prepare ordinary people for an extraordinary destiny.",
  "The secret of success is to do the common thing uncommonly well.",
  "I attribute my success to this: I never gave or took any excuse.",
  "Success is how high you bounce when you hit bottom.",
  "If you're going through hell, keep going.",
  "The ones who are crazy enough to think they can change the world are the ones who do.",
  "Great things are done by a series of small things brought together.",
  "The ladder of success is best climbed by stepping on the rungs of opportunity.",
  "Your talent is God's gift to you. What you do with it is your gift back to God.",
  "Success is a state of mind. If you want success, start thinking of yourself as a success.",
  "It always seems impossible until it's done.",
  "If you look at what you have in life, you'll always have more.",
  "The question isn't who is going to let me; it's who is going to stop me.",
  "Excellence is not a destination; it is a continuous journey.",
  "Be the change that you wish to see in the world.",
  "Happiness is not something readymade. It comes from your own actions.",
  "In the middle of every difficulty lies opportunity.",
  "Do not wait to strike till the iron is hot; but make it hot by striking.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "Genius is 1% inspiration and 99% perspiration.",
  "Success is simple. Do what's right, the right way, at the right time.",
  "Always do your best. What you plant now, you will harvest later.",
  "The best time to plant a tree was 20 years ago. The second best time is now.",
  "Persistence guarantees that results are inevitable.",
  "You miss 100% of the shots you don't take.",
  "The more I practice, the luckier I get."
];
